### ISSUE TITLE
After creating/editing widget, area controls for widget disappear

### ISSUE THREAD

**Issue by jsumnersmith** [punkave/apostrophe-rss#3]
After editing and RSS widget, a user is unable to edit the widget again without refreshing the page. I'm assuming that something is running outside the player and that is causing the breakage. I couldn't track down the specific issue. 

This is replicable in a fresh sandbox.

**Comment by boutell** [comment]
This is fixed. The RSS widget was replacing the entire widget when AJAXing in the content. This removed the editing buttons.

There is now a wrapper div inside the widget that gets its content replaced instead.

Since the changes were entirely in the browser and server side javascript this should not impact any legacy rss.html templates or styles, unless someone did something silly like styling a "div" without any classes to do something excessively wacky.
